# Tile structure:
# Base indedstructable stone tile
# - Dirt
#   - Grass variants
# - Gravel
# - Sand
# - other natural tiles
# - Fundament
#   - Wood planks
#   - Stonebricks
#   - other produced tiles

- type: tile
  editorHidden: false
  id: CP14FloorBase
  name: cp14-tiles-base
  sprite: /Textures/_CP14/Tiles/cave.png
  variants: 14
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  baseTurf: CP14FloorBase #Recursivle indestructible
  isSubfloor: true
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  indestructible: true

- type: tile
  id: CP14FloorAtlasMask
  editorHidden: false
  name: cp14-tiles-atlas-mask
  sprite: /Textures/Tiles/shuttleorange.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  baseTurf: CP14FloorBase
  isSubfloor: false
  heatCapacity: 10000

- type: tile
  id: CP14FloorAtlasMask2
  editorHidden: false
  name: cp14-tiles-atlas-mask-2
  sprite: /Textures/Tiles/shuttleblue.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  baseTurf: CP14FloorBase
  isSubfloor: false
  heatCapacity: 10000